---
- name: Install dependencies
  yum: name={{ item }} state=installed
  with_items: 
   - 'java'
   - 'git'
   - 'curl'
   - 'epel-release'

- name: Install ansbile
  yum: name=ansible state=installed