---
- name: Install repo for Centos
  include: repo.centos.yml

- include: dependencies.yml

- name: Install Jenkins for Centos
  yum: name=jenkins state=latest
  register: jenkins_install

- name: Ensure jenkins is running
  service:
    name: jenkins
    state: started
    enabled: yes

# - include: settings.yml

- name: Ensure Jenkins user can run bash
  lineinfile:
    dest: /etc/passwd
    state: present
    regexp: '^(.*)/var/lib/jenkins:/bin/false(.*)$'
    line: '\1/var/lib/jenkins:/bin/bash\2'
    backup: yes
    backrefs: yes